# Site settings
title: Lu Nie Blog
name: Lu Nie  # your name
email: nielu3@mail.sysu.edu.cn  # your email address
description: >
    A Simple Persoanl Blog. # this means to ignore newlines until "baseurl:"
baseurl: "/lunie2021.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: LuNie2021 # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
